spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${configure.dev.address:localhost}:3306/dubbo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
dubbo:
  application:
    name: dubbo-provider
  #    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://${configure.prod.address:127.0.0.1}:2181

#写你自己安装zookeeper的服务器地址
server:
  port: 8080
configure:
  dev:
    address: xxxx
  prod:
    address: xxxx

