spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

dubbo:
  application:
    name: dubbo-gateAway
    logger: slf4j
    qos-port: 33333
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
#写你自己安装zookeeper的服务器地址
zookeeper:
  address: xxxxxx
server:
  port: 8082

